import { prisma } from '../lib/prisma'

const ROLLING_STOCK_DATA = [
  // ICE Series
  {
    id: 'ice-1',
    operator: 'DB',
    series: 'ICE 1',
    uicClass: '401',
    manufacturer: 'AEG, Henschel, Krauss-Maffei, Krupp',
    introducedYear: 1991,
    maxSpeedKmh: 280,
    seats1st: 192,
    seats2nd: 384,
    hasBistro: true,
    hasWifi: false,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '15 kV AC, 25 kV AC',
    traction: 'Electric',
    description: 'German InterCityExpress high-speed train, first generation ICE.',
    wikiUrl: 'https://en.wikipedia.org/wiki/ICE_1',
    dataSource: 'seed',
  },
  {
    id: 'ice-2',
    operator: 'DB',
    series: 'ICE 2',
    uicClass: '402',
    manufacturer: 'AEG, Henschel, Krauss-Maffei, Krupp',
    introducedYear: 1995,
    maxSpeedKmh: 280,
    seats1st: 136,
    seats2nd: 358,
    hasBistro: true,
    hasWifi: false,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '15 kV AC, 25 kV AC',
    traction: 'Electric',
    description: 'German InterCityExpress high-speed train, second generation.',
    wikiUrl: 'https://en.wikipedia.org/wiki/ICE_2',
    dataSource: 'seed',
  },
  {
    id: 'ice-3',
    operator: 'DB',
    series: 'ICE 3',
    uicClass: '403/406',
    manufacturer: 'Adtranz, Siemens',
    introducedYear: 2000,
    maxSpeedKmh: 330,
    seats1st: 192,
    seats2nd: 384,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '15 kV AC, 25 kV AC, 1.5 kV DC, 3 kV DC',
    traction: 'Electric',
    description: 'German InterCityExpress high-speed train, third generation with multi-voltage capability.',
    wikiUrl: 'https://en.wikipedia.org/wiki/ICE_3',
    dataSource: 'seed',
  },
  {
    id: 'ice-4',
    operator: 'DB',
    series: 'ICE 4',
    uicClass: '412',
    manufacturer: 'Siemens Mobility',
    introducedYear: 2017,
    maxSpeedKmh: 250,
    seats1st: 205,
    seats2nd: 463,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC, 25 kV AC',
    traction: 'Electric',
    description: 'German InterCityExpress high-speed train, latest generation with modern amenities.',
    wikiUrl: 'https://en.wikipedia.org/wiki/ICE_4',
    dataSource: 'seed',
  },
  {
    id: 'ice-t',
    operator: 'DB',
    series: 'ICE T',
    uicClass: '411/415',
    manufacturer: 'Siemens, Bombardier',
    introducedYear: 1999,
    maxSpeedKmh: 230,
    seats1st: 140,
    seats2nd: 300,
    hasBistro: true,
    hasWifi: false,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '15 kV AC',
    traction: 'Electric Tilt',
    description: 'German tilting train for enhanced speed on conventional lines.',
    wikiUrl: 'https://en.wikipedia.org/wiki/ICE_T',
    dataSource: 'seed',
  },

  // DB Intercity
  {
    id: 'db-ic2',
    operator: 'DB',
    series: 'IC2',
    uicClass: '4110',
    manufacturer: 'Bombardier',
    introducedYear: 2016,
    maxSpeedKmh: 160,
    seats1st: 71,
    seats2nd: 291,
    hasBistro: false,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'German double-deck Intercity trains for regional services.',
    wikiUrl: 'https://en.wikipedia.org/wiki/DB_Class_4110',
    dataSource: 'seed',
  },
  {
    id: 'db-intercity',
    operator: 'DB',
    series: 'Intercity',
    uicClass: 'IC',
    manufacturer: 'Various',
    introducedYear: 1971,
    maxSpeedKmh: 200,
    seats1st: 48,
    seats2nd: 192,
    hasBistro: true,
    hasWifi: false,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'Classic German Intercity coaches with restaurant car.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Intercity_(Deutsche_Bahn)',
    dataSource: 'seed',
  },

  // ÖBB Trains
  {
    id: 'obb-railjet',
    operator: 'ÖBB',
    series: 'Railjet',
    uicClass: 'RJ',
    manufacturer: 'Siemens Mobility',
    introducedYear: 2008,
    maxSpeedKmh: 230,
    seats1st: 76,
    seats2nd: 316,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'Austrian high-speed train connecting major cities.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Railjet',
    dataSource: 'seed',
  },
  {
    id: 'obb-nightjet',
    operator: 'ÖBB',
    series: 'Nightjet',
    uicClass: 'NJ',
    manufacturer: 'Siemens Mobility',
    introducedYear: 2016,
    maxSpeedKmh: 200,
    seats1st: 0,
    seats2nd: 0,
    hasBistro: false,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'Austrian night train with sleeping and couchette cars.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Nightjet',
    dataSource: 'seed',
  },
  {
    id: 'obb-cityjet',
    operator: 'ÖBB',
    series: 'Cityjet',
    uicClass: '4744',
    manufacturer: 'Siemens Mobility',
    introducedYear: 2015,
    maxSpeedKmh: 160,
    seats1st: 62,
    seats2nd: 182,
    hasBistro: false,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'Austrian regional train for urban and suburban services.',
    wikiUrl: 'https://en.wikipedia.org/wiki/DB_Class_474',
    dataSource: 'seed',
  },

  // SBB Trains
  {
    id: 'sbb-giruno',
    operator: 'SBB',
    series: 'Giruno',
    uicClass: '501',
    manufacturer: 'Stadler Rail',
    introducedYear: 2019,
    maxSpeedKmh: 250,
    seats1st: 88,
    seats2nd: 313,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'Swiss high-speed train for international services.',
    wikiUrl: 'https://en.wikipedia.org/wiki/SBB_CFF_FFS_RABe_501',
    dataSource: 'seed',
  },
  {
    id: 'sbb-astoro',
    operator: 'SBB',
    series: 'Astoro',
    uicClass: '523',
    manufacturer: 'Bombardier',
    introducedYear: 2019,
    maxSpeedKmh: 200,
    seats1st: 45,
    seats2nd: 149,
    hasBistro: false,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'Swiss regional train with modern amenities.',
    wikiUrl: 'https://en.wikipedia.org/wiki/SBB_CFF_FFS_RABe_523',
    dataSource: 'seed',
  },

  // TGV Series
  {
    id: 'tgv-duplex',
    operator: 'SNCF',
    series: 'TGV Duplex',
    uicClass: 'TGV-D',
    manufacturer: 'Alstom',
    introducedYear: 1995,
    maxSpeedKmh: 320,
    seats1st: 168,
    seats2nd: 545,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '25 kV AC, 1.5 kV DC',
    traction: 'Electric',
    description: 'French double-deck high-speed train, iconic TGV design.',
    wikiUrl: 'https://en.wikipedia.org/wiki/TGV_Duplex',
    dataSource: 'seed',
  },
  {
    id: 'tgv-inoui',
    operator: 'SNCF',
    series: 'TGV InOui',
    uicClass: 'TGV-I',
    manufacturer: 'Alstom',
    introducedYear: 2017,
    maxSpeedKmh: 320,
    seats1st: 110,
    seats2nd: 444,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '25 kV AC, 1.5 kV DC, 3 kV DC',
    traction: 'Electric',
    description: 'French premium high-speed train with modern amenities.',
    wikiUrl: 'https://en.wikipedia.org/wiki/TGV_InOui',
    dataSource: 'seed',
  },

  // Eurostar
  {
    id: 'eurostar-e320',
    operator: 'Eurostar',
    series: 'e320',
    uicClass: '374',
    manufacturer: 'Siemens Mobility',
    introducedYear: 2015,
    maxSpeedKmh: 320,
    seats1st: 106,
    seats2nd: 766,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '25 kV AC, 1.5 kV DC, 3 kV DC, 15 kV AC',
    traction: 'Electric',
    description: 'Next-generation Eurostar train for cross-channel services.',
    wikiUrl: 'https://en.wikipedia.org/wiki/British_Rail_Class_374',
    dataSource: 'seed',
  },

  // Thalys
  {
    id: 'thalys-pbka',
    operator: 'Thalys',
    series: 'PBKA',
    uicClass: 'PBKA',
    manufacturer: 'Alstom',
    introducedYear: 1997,
    maxSpeedKmh: 300,
    seats1st: 120,
    seats2nd: 404,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '25 kV AC, 1.5 kV DC, 3 kV DC, 15 kV AC',
    traction: 'Electric',
    description: 'High-speed train connecting Paris, Brussels, Köln, and Amsterdam.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Thalys_PBKA',
    dataSource: 'seed',
  },

  // Generic Types
  {
    id: 'flirt-generic',
    operator: 'Various',
    series: 'FLIRT',
    uicClass: 'FLIRT',
    manufacturer: 'Stadler Rail',
    introducedYear: 2004,
    maxSpeedKmh: 160,
    seats1st: 30,
    seats2nd: 120,
    hasBistro: false,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: 'Various',
    traction: 'Electric/Diesel',
    description: 'Swiss modular train family used across Europe.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Stadler_FLIRT',
    dataSource: 'seed',
  },
  {
    id: 'desiro-generic',
    operator: 'Various',
    series: 'Desiro',
    uicClass: 'Desiro',
    manufacturer: 'Siemens Mobility',
    introducedYear: 1998,
    maxSpeedKmh: 160,
    seats1st: 24,
    seats2nd: 144,
    hasBistro: false,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: 'Various',
    traction: 'Electric/Diesel',
    description: 'German modular train family for regional services.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Siemens_Desiro',
    dataSource: 'seed',
  },
]

async function main() {
  console.log('🚂 Seeding rolling stock data...')

  for (const stock of ROLLING_STOCK_DATA) {
    await prisma.rollingStock.upsert({
      where: { id: stock.id },
      update: stock,
      create: stock,
    })
    console.log(`✅ ${stock.series} (${stock.operator})`)
  }

  console.log('✨ Rolling stock seeding complete!')
}

main()
  .catch((e) => {
    console.error('❌ Error seeding rolling stock:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })