import { prisma } from '../lib/prisma'

const ROLLING_STOCK_DATA = [
  // ── DB ICE family ─────────────────────────────────────────────────────────
  {
    id: 'ice-1',
    operator: 'DB',
    series: 'ICE 1',
    uicClass: '401',
    manufacturer: 'AEG, Henschel, Krauss-Maffei, Krupp',
    introducedYear: 1991,
    maxSpeedKmh: 280,
    seats1st: 192,
    seats2nd: 384,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'BR 401 — original ICE from 1991, full-length train with bistro car.',
    wikiUrl: 'https://en.wikipedia.org/wiki/ICE_1',
    dataSource: 'seed',
  },
  {
    id: 'ice-2',
    operator: 'DB',
    series: 'ICE 2',
    uicClass: '402',
    manufacturer: 'AEG, Henschel, Krauss-Maffei, Krupp',
    introducedYear: 1995,
    maxSpeedKmh: 280,
    seats1st: 136,
    seats2nd: 358,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'BR 402 — half-set ICE with driving trailer, often coupled in pairs.',
    wikiUrl: 'https://en.wikipedia.org/wiki/ICE_2',
    dataSource: 'seed',
  },
  {
    id: 'ice-3',
    operator: 'DB',
    series: 'ICE 3',
    uicClass: '403',
    manufacturer: 'Adtranz, Siemens',
    introducedYear: 2000,
    maxSpeedKmh: 330,
    seats1st: 192,
    seats2nd: 384,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '15 kV AC, 25 kV AC, 1.5 kV DC, 3 kV DC',
    traction: 'Electric',
    description: 'BR 403/406 — distributed-traction ICE 3, up to 330 km/h, multi-voltage.',
    wikiUrl: 'https://en.wikipedia.org/wiki/ICE_3',
    dataSource: 'seed',
  },
  {
    id: 'ice-3-velaro',
    operator: 'DB',
    series: 'ICE 3 Velaro',
    uicClass: '407',
    manufacturer: 'Siemens Mobility',
    introducedYear: 2013,
    maxSpeedKmh: 320,
    seats1st: 196,
    seats2nd: 405,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '15 kV AC, 25 kV AC, 1.5 kV DC, 3 kV DC',
    traction: 'Electric',
    description: 'BR 407 — Velaro D by Siemens, improved aerodynamics and passenger comfort.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Siemens_Velaro#Velaro_D_(DB_Class_407)',
    dataSource: 'seed',
  },
  {
    id: 'ice-3-neo',
    operator: 'DB',
    series: 'ICE 3 Neo',
    uicClass: '408',
    manufacturer: 'Siemens Mobility',
    introducedYear: 2022,
    maxSpeedKmh: 320,
    seats1st: 213,
    seats2nd: 424,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC, 25 kV AC',
    traction: 'Electric',
    description: 'BR 408 — next-generation Velaro by Siemens, with bike spaces, new bistro.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Siemens_Velaro_MS',
    dataSource: 'seed',
  },
  {
    id: 'ice-t',
    operator: 'DB',
    series: 'ICE T',
    uicClass: '411',
    manufacturer: 'Siemens, Bombardier',
    introducedYear: 1999,
    maxSpeedKmh: 230,
    seats1st: 140,
    seats2nd: 300,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '15 kV AC',
    traction: 'Electric Tilt',
    description: 'BR 411/415 — tilting ICE for curves, used on Stuttgart–Zürich.',
    wikiUrl: 'https://en.wikipedia.org/wiki/ICE_T',
    dataSource: 'seed',
  },
  {
    id: 'ice-4-13',
    operator: 'DB',
    series: 'ICE 4',
    uicClass: '412',
    manufacturer: 'Siemens Mobility',
    introducedYear: 2017,
    maxSpeedKmh: 250,
    seats1st: 205,
    seats2nd: 463,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC, 25 kV AC',
    traction: 'Electric',
    description: 'BR 412 (13-car) — long-form ICE 4, largest fleet in DB high-speed service.',
    wikiUrl: 'https://en.wikipedia.org/wiki/ICE_4',
    dataSource: 'seed',
  },

  // ── DB Intercity / EuroCity / regional ────────────────────────────────────
  {
    id: 'db-ic2',
    operator: 'DB',
    series: 'IC 2',
    uicClass: '4110',
    manufacturer: 'Bombardier',
    introducedYear: 2016,
    maxSpeedKmh: 160,
    seats1st: 71,
    seats2nd: 291,
    hasBistro: false,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'Twindexx double-deck push-pull — IC 2 routes, modern amenities.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Bombardier_Twindexx',
    dataSource: 'seed',
  },
  {
    id: 'db-intercity',
    operator: 'DB',
    series: 'Intercity',
    uicClass: 'IC',
    manufacturer: 'Various',
    introducedYear: 1971,
    maxSpeedKmh: 200,
    seats1st: 48,
    seats2nd: 192,
    hasBistro: true,
    hasWifi: false,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'Classic DB Intercity — Bimz/Avmz coaches with restaurant car.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Intercity_(Deutsche_Bahn)',
    dataSource: 'seed',
  },
  {
    id: 'db-ec',
    operator: 'DB',
    series: 'EuroCity',
    uicClass: 'EC',
    manufacturer: 'Various',
    introducedYear: 1987,
    maxSpeedKmh: 200,
    seats1st: 60,
    seats2nd: 200,
    hasBistro: true,
    hasWifi: false,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'International EuroCity — classic coaches or Railjet on cross-border routes.',
    wikiUrl: 'https://en.wikipedia.org/wiki/EuroCity',
    dataSource: 'seed',
  },
  {
    id: 'db-nightjet',
    operator: 'ÖBB',
    series: 'Nightjet',
    uicClass: 'NJ',
    manufacturer: 'Siemens Mobility',
    introducedYear: 2016,
    maxSpeedKmh: 200,
    seats1st: 0,
    seats2nd: 0,
    hasBistro: false,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC, 25 kV AC',
    traction: 'Electric',
    description: 'ÖBB overnight sleeper — seats, couchettes and private sleeping compartments.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Nightjet',
    dataSource: 'seed',
  },
  {
    id: 'db-talent3',
    operator: 'DB',
    series: 'Talent 3',
    uicClass: '463',
    manufacturer: 'Bombardier',
    introducedYear: 2018,
    maxSpeedKmh: 160,
    seats1st: 0,
    seats2nd: 232,
    hasBistro: false,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'BR 463 — DB S-Bahn and regional express, low-floor accessibility.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Bombardier_Talent',
    dataSource: 'seed',
  },
  {
    id: 'db-462',
    operator: 'DB',
    series: 'Desiro HC',
    uicClass: '462',
    manufacturer: 'Siemens Mobility',
    introducedYear: 2019,
    maxSpeedKmh: 160,
    seats1st: 56,
    seats2nd: 232,
    hasBistro: false,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'BR 462 Desiro HC — high-capacity regional double-deck by Siemens.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Siemens_Desiro_HC',
    dataSource: 'seed',
  },
  {
    id: 'db-442',
    operator: 'DB',
    series: 'Talent 2',
    uicClass: '442',
    manufacturer: 'Bombardier',
    introducedYear: 2012,
    maxSpeedKmh: 160,
    seats1st: 40,
    seats2nd: 200,
    hasBistro: false,
    hasWifi: false,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'BR 442 Talent 2 — DB Regio workhorse, widespread on RE/RB routes.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Bombardier_Talent_2',
    dataSource: 'seed',
  },
  {
    id: 'db-440',
    operator: 'DB',
    series: 'Coradia Continental',
    uicClass: '440',
    manufacturer: 'Alstom',
    introducedYear: 2007,
    maxSpeedKmh: 160,
    seats1st: 0,
    seats2nd: 190,
    hasBistro: false,
    hasWifi: false,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'BR 440/445 Coradia Continental — Alstom EMU on DB Regio regional routes.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Alstom_Coradia_Continental',
    dataSource: 'seed',
  },
  {
    id: 'db-429',
    operator: 'DB',
    series: 'Stadler FLIRT',
    uicClass: '429',
    manufacturer: 'Stadler Rail',
    introducedYear: 2008,
    maxSpeedKmh: 160,
    seats1st: 36,
    seats2nd: 184,
    hasBistro: false,
    hasWifi: false,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'BR 429 FLIRT — Stadler light EMU used on DB Regio routes in Rhineland.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Stadler_FLIRT',
    dataSource: 'seed',
  },

  // ── ÖBB ───────────────────────────────────────────────────────────────────
  {
    id: 'obb-railjet',
    operator: 'ÖBB',
    series: 'Railjet',
    uicClass: 'RJ',
    manufacturer: 'Siemens Mobility',
    introducedYear: 2008,
    maxSpeedKmh: 230,
    seats1st: 76,
    seats2nd: 316,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'Siemens Viaggio Comfort — ÖBB/ČD high-speed, 3 classes, bistro.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Railjet',
    dataSource: 'seed',
  },
  {
    id: 'obb-rjx',
    operator: 'ÖBB',
    series: 'Railjet Xpress',
    uicClass: 'RJX',
    manufacturer: 'Siemens Mobility',
    introducedYear: 2014,
    maxSpeedKmh: 230,
    seats1st: 76,
    seats2nd: 316,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC, 25 kV AC',
    traction: 'Electric',
    description: 'Railjet Xpress — international Railjet variant for Munich/Frankfurt runs.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Railjet',
    dataSource: 'seed',
  },
  {
    id: 'obb-cityjet',
    operator: 'ÖBB',
    series: 'Cityjet',
    uicClass: '4744',
    manufacturer: 'Siemens Mobility',
    introducedYear: 2015,
    maxSpeedKmh: 160,
    seats1st: 62,
    seats2nd: 182,
    hasBistro: false,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'Siemens Desiro ML — ÖBB regional and suburban workhorse.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Siemens_Desiro_ML',
    dataSource: 'seed',
  },
  {
    id: 'obb-talent3',
    operator: 'ÖBB',
    series: 'Talent 3',
    uicClass: '4746',
    manufacturer: 'Bombardier',
    introducedYear: 2019,
    maxSpeedKmh: 160,
    seats1st: 0,
    seats2nd: 320,
    hasBistro: false,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC, 25 kV AC',
    traction: 'Electric',
    description: 'ÖBB Talent 3 — high-capacity S-Bahn and regional, bi-voltage.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Bombardier_Talent',
    dataSource: 'seed',
  },
  {
    id: 'obb-4020',
    operator: 'ÖBB',
    series: '4020',
    uicClass: '4020',
    manufacturer: 'SGP',
    introducedYear: 1978,
    maxSpeedKmh: 120,
    seats1st: 0,
    seats2nd: 168,
    hasBistro: false,
    hasWifi: false,
    hasWheelchair: false,
    hasBikeSpace: true,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'ÖBB 4020 — classic S-Bahn EMU, still in service in Vienna.',
    wikiUrl: 'https://en.wikipedia.org/wiki/ÖBB_4020',
    dataSource: 'seed',
  },

  // ── SBB ───────────────────────────────────────────────────────────────────
  {
    id: 'sbb-giruno',
    operator: 'SBB',
    series: 'Giruno',
    uicClass: '501',
    manufacturer: 'Stadler Rail',
    introducedYear: 2019,
    maxSpeedKmh: 250,
    seats1st: 88,
    seats2nd: 313,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC, 25 kV AC, 3 kV DC',
    traction: 'Electric',
    description: 'RABe 501 — SBB international high-speed for Gotthard routes.',
    wikiUrl: 'https://en.wikipedia.org/wiki/SBB_CFF_FFS_RABe_501',
    dataSource: 'seed',
  },
  {
    id: 'sbb-ic2000',
    operator: 'SBB',
    series: 'IC 2000',
    uicClass: 'IC2000',
    manufacturer: 'Bombardier',
    introducedYear: 1996,
    maxSpeedKmh: 200,
    seats1st: 110,
    seats2nd: 440,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'SBB double-deck IC push-pull — bread-and-butter Swiss intercity.',
    wikiUrl: 'https://en.wikipedia.org/wiki/SBB_IC_2000',
    dataSource: 'seed',
  },
  {
    id: 'sbb-icn',
    operator: 'SBB',
    series: 'ICN',
    uicClass: '500',
    manufacturer: 'Bombardier',
    introducedYear: 2000,
    maxSpeedKmh: 200,
    seats1st: 60,
    seats2nd: 244,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC',
    traction: 'Electric Tilt',
    description: 'RABDe 500 — SBB tilting InterCity Neigezug for mountain routes.',
    wikiUrl: 'https://en.wikipedia.org/wiki/SBB_RABDe_500',
    dataSource: 'seed',
  },
  {
    id: 'sbb-twindexx',
    operator: 'SBB',
    series: 'Twindexx Express',
    uicClass: '511',
    manufacturer: 'Bombardier',
    introducedYear: 2019,
    maxSpeedKmh: 200,
    seats1st: 106,
    seats2nd: 422,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'RABe 511 — SBB double-deck Twindexx Express for IR routes.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Bombardier_Twindexx',
    dataSource: 'seed',
  },
  {
    id: 'sbb-fv-dosto',
    operator: 'SBB',
    series: 'FV-Dosto',
    uicClass: '512',
    manufacturer: 'Stadler Rail',
    introducedYear: 2020,
    maxSpeedKmh: 200,
    seats1st: 120,
    seats2nd: 480,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'RABe 512 — SBB Stadler double-deck for IC routes, replacing IC 2000.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Stadler_DOSTO',
    dataSource: 'seed',
  },
  {
    id: 'sbb-etr610',
    operator: 'SBB',
    series: 'ETR 610',
    uicClass: '503',
    manufacturer: 'Alstom',
    introducedYear: 2009,
    maxSpeedKmh: 250,
    seats1st: 95,
    seats2nd: 325,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '15 kV AC, 25 kV AC, 1.5 kV DC, 3 kV DC',
    traction: 'Electric Tilt',
    description: 'Astoro/ETR 610 — Swiss/Italian tilting pendolino for international routes.',
    wikiUrl: 'https://en.wikipedia.org/wiki/ETR_610',
    dataSource: 'seed',
  },

  // ── SNCF / France ─────────────────────────────────────────────────────────
  {
    id: 'tgv-duplex',
    operator: 'SNCF',
    series: 'TGV Duplex',
    uicClass: 'TGV-D',
    manufacturer: 'Alstom',
    introducedYear: 1995,
    maxSpeedKmh: 320,
    seats1st: 168,
    seats2nd: 545,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '25 kV AC, 1.5 kV DC',
    traction: 'Electric',
    description: 'Double-deck TGV — flagship SNCF high-speed since 1995.',
    wikiUrl: 'https://en.wikipedia.org/wiki/TGV_Duplex',
    dataSource: 'seed',
  },
  {
    id: 'tgv-inoui',
    operator: 'SNCF',
    series: 'TGV Inouï',
    uicClass: 'TGV-I',
    manufacturer: 'Alstom',
    introducedYear: 2017,
    maxSpeedKmh: 320,
    seats1st: 110,
    seats2nd: 444,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '25 kV AC, 1.5 kV DC, 3 kV DC',
    traction: 'Electric',
    description: 'SNCF premium TGV brand — Euroduplex/Océane stock with redesigned interior.',
    wikiUrl: 'https://en.wikipedia.org/wiki/TGV_Inouï',
    dataSource: 'seed',
  },
  {
    id: 'tgv-pos',
    operator: 'SNCF',
    series: 'TGV POS',
    uicClass: 'TGV-POS',
    manufacturer: 'Alstom',
    introducedYear: 2007,
    maxSpeedKmh: 320,
    seats1st: 120,
    seats2nd: 356,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '25 kV AC, 1.5 kV DC, 15 kV AC',
    traction: 'Electric',
    description: 'TGV Paris–Ostfrankreich–Süddeutschland — tri-voltage for Germany/Switzerland.',
    wikiUrl: 'https://en.wikipedia.org/wiki/TGV_POS',
    dataSource: 'seed',
  },
  {
    id: 'ouigo',
    operator: 'SNCF',
    series: 'OUIGO',
    uicClass: 'TGV-D',
    manufacturer: 'Alstom',
    introducedYear: 2013,
    maxSpeedKmh: 320,
    seats1st: 0,
    seats2nd: 1268,
    hasBistro: false,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '25 kV AC, 1.5 kV DC',
    traction: 'Electric',
    description: 'SNCF low-cost TGV — Duplex stock with dense 2+3 seating, no bistro.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Ouigo',
    dataSource: 'seed',
  },
  {
    id: 'thalys-pbka',
    operator: 'Eurostar',
    series: 'Thalys PBKA',
    uicClass: 'PBKA',
    manufacturer: 'Alstom',
    introducedYear: 1997,
    maxSpeedKmh: 300,
    seats1st: 120,
    seats2nd: 404,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '25 kV AC, 1.5 kV DC, 3 kV DC, 15 kV AC',
    traction: 'Electric',
    description: 'Quad-voltage TGV — Paris/Brussels/Amsterdam/Cologne (ex-Thalys, now Eurostar).',
    wikiUrl: 'https://en.wikipedia.org/wiki/Thalys_PBKA',
    dataSource: 'seed',
  },

  // ── Eurostar ──────────────────────────────────────────────────────────────
  {
    id: 'eurostar-e320',
    operator: 'Eurostar',
    series: 'Eurostar e320',
    uicClass: '374',
    manufacturer: 'Siemens Mobility',
    introducedYear: 2015,
    maxSpeedKmh: 320,
    seats1st: 106,
    seats2nd: 766,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '25 kV AC, 1.5 kV DC, 3 kV DC, 15 kV AC',
    traction: 'Electric',
    description: 'Velaro e320 — Channel Tunnel high-speed to London/Paris/Brussels/Amsterdam.',
    wikiUrl: 'https://en.wikipedia.org/wiki/British_Rail_Class_374',
    dataSource: 'seed',
  },
  {
    id: 'eurostar-e300',
    operator: 'Eurostar',
    series: 'Eurostar e300',
    uicClass: '373',
    manufacturer: 'GEC Alsthom',
    introducedYear: 1994,
    maxSpeedKmh: 300,
    seats1st: 210,
    seats2nd: 584,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '25 kV AC, 1.5 kV DC, 3 kV DC, 750 V DC',
    traction: 'Electric',
    description: 'Class 373 — original Eurostar trainset, TGV-derived, now retired.',
    wikiUrl: 'https://en.wikipedia.org/wiki/British_Rail_Class_373',
    dataSource: 'seed',
  },

  // ── Italy ─────────────────────────────────────────────────────────────────
  {
    id: 'trenitalia-fr1000',
    operator: 'Trenitalia',
    series: 'Frecciarossa 1000',
    uicClass: '400',
    manufacturer: 'AnsaldoBreda, Bombardier',
    introducedYear: 2015,
    maxSpeedKmh: 400,
    seats1st: 97,
    seats2nd: 360,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '25 kV AC, 3 kV DC',
    traction: 'Electric',
    description: 'ETR 400 — world speed record 393 km/h (2016), Italian flagship.',
    wikiUrl: 'https://en.wikipedia.org/wiki/ETR_400',
    dataSource: 'seed',
  },
  {
    id: 'trenitalia-etr500',
    operator: 'Trenitalia',
    series: 'ETR 500',
    uicClass: '500',
    manufacturer: 'Various Italian',
    introducedYear: 1996,
    maxSpeedKmh: 360,
    seats1st: 116,
    seats2nd: 478,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '25 kV AC, 3 kV DC',
    traction: 'Electric',
    description: 'ETR 500 — classic Frecciarossa on Italian high-speed network.',
    wikiUrl: 'https://en.wikipedia.org/wiki/ETR_500',
    dataSource: 'seed',
  },
  {
    id: 'trenitalia-fa',
    operator: 'Trenitalia',
    series: 'Frecciargento',
    uicClass: '600',
    manufacturer: 'Alstom',
    introducedYear: 2006,
    maxSpeedKmh: 250,
    seats1st: 108,
    seats2nd: 344,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '25 kV AC, 3 kV DC',
    traction: 'Electric Tilt',
    description: 'ETR 600 — tilting pendolino for non-HSL routes, Rome to Reggio Calabria.',
    wikiUrl: 'https://en.wikipedia.org/wiki/ETR_600',
    dataSource: 'seed',
  },
  {
    id: 'trenitalia-fb',
    operator: 'Trenitalia',
    series: 'Frecciabianca',
    uicClass: '460',
    manufacturer: 'Fiat Ferroviaria',
    introducedYear: 1988,
    maxSpeedKmh: 200,
    seats1st: 114,
    seats2nd: 344,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '3 kV DC',
    traction: 'Electric Tilt',
    description: 'ETR 460 — Pendolino on conventional lines, intercity high-speed.',
    wikiUrl: 'https://en.wikipedia.org/wiki/ETR_460',
    dataSource: 'seed',
  },
  {
    id: 'italo-agv',
    operator: 'Italo NTV',
    series: 'Italo AGV',
    uicClass: 'AGV',
    manufacturer: 'Alstom',
    introducedYear: 2012,
    maxSpeedKmh: 360,
    seats1st: 56,
    seats2nd: 396,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '25 kV AC, 3 kV DC',
    traction: 'Electric',
    description: 'Alstom AGV — Italian private high-speed, distributed traction.',
    wikiUrl: 'https://en.wikipedia.org/wiki/AGV_(train)',
    dataSource: 'seed',
  },
  {
    id: 'italo-evo',
    operator: 'Italo NTV',
    series: 'Italo EVO',
    uicClass: 'EVO',
    manufacturer: 'Alstom',
    introducedYear: 2018,
    maxSpeedKmh: 360,
    seats1st: 56,
    seats2nd: 457,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '25 kV AC, 3 kV DC',
    traction: 'Electric',
    description: 'Italo EVO — enhanced AGV fleet with more 2nd class capacity.',
    wikiUrl: 'https://en.wikipedia.org/wiki/AGV_(train)',
    dataSource: 'seed',
  },

  // ── Spain ─────────────────────────────────────────────────────────────────
  {
    id: 'renfe-ave-s103',
    operator: 'Renfe',
    series: 'AVE S-103',
    uicClass: '103',
    manufacturer: 'Siemens Mobility',
    introducedYear: 2007,
    maxSpeedKmh: 350,
    seats1st: 116,
    seats2nd: 288,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '25 kV AC',
    traction: 'Electric',
    description: 'Velaro E — Spanish AVE high-speed, Madrid–Barcelona flagship.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Siemens_Velaro#Velaro_E_(Renfe_Class_103)',
    dataSource: 'seed',
  },
  {
    id: 'renfe-ave-s102',
    operator: 'Renfe',
    series: 'AVE S-102',
    uicClass: '102',
    manufacturer: 'CAF/Alstom',
    introducedYear: 2005,
    maxSpeedKmh: 330,
    seats1st: 64,
    seats2nd: 254,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '25 kV AC',
    traction: 'Electric',
    description: 'Talgo 350 — Spanish AVE, aerodynamic nose, variable gauge capable.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Talgo_350',
    dataSource: 'seed',
  },
  {
    id: 'renfe-avlo',
    operator: 'Renfe',
    series: 'AVLO',
    uicClass: '106',
    manufacturer: 'Alstom',
    introducedYear: 2021,
    maxSpeedKmh: 300,
    seats1st: 0,
    seats2nd: 438,
    hasBistro: false,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '25 kV AC',
    traction: 'Electric',
    description: 'Renfe low-cost AVE — Euroduplex stock, high-density configuration.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Avlo',
    dataSource: 'seed',
  },
  {
    id: 'iryo',
    operator: 'Iryo',
    series: 'Iryo Frecciarossa',
    uicClass: '106',
    manufacturer: 'AnsaldoBreda, Bombardier',
    introducedYear: 2022,
    maxSpeedKmh: 300,
    seats1st: 97,
    seats2nd: 360,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '25 kV AC',
    traction: 'Electric',
    description: 'Iryo — Spanish private HSR operator using Frecciarossa 1000 stock.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Iryo',
    dataSource: 'seed',
  },

  // ── Netherlands ───────────────────────────────────────────────────────────
  {
    id: 'ns-icng',
    operator: 'NS',
    series: 'ICNG',
    uicClass: 'ICNG',
    manufacturer: 'Alstom',
    introducedYear: 2021,
    maxSpeedKmh: 250,
    seats1st: 60,
    seats2nd: 457,
    hasBistro: false,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '25 kV AC, 1.5 kV DC',
    traction: 'Electric',
    description: 'NS InterCity Nieuwe Generatie — Alstom Coradia Stream for Amsterdam–Brussels.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Alstom_Coradia_Stream',
    dataSource: 'seed',
  },
  {
    id: 'ns-virm',
    operator: 'NS',
    series: 'VIRM',
    uicClass: 'VIRM',
    manufacturer: 'Bombardier',
    introducedYear: 2000,
    maxSpeedKmh: 160,
    seats1st: 80,
    seats2nd: 324,
    hasBistro: false,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '1.5 kV DC',
    traction: 'Electric',
    description: 'NS double-deck InterCity — Bombardier VIRM, Dutch intercity workhorse.',
    wikiUrl: 'https://en.wikipedia.org/wiki/VIRM',
    dataSource: 'seed',
  },

  // ── Belgium ───────────────────────────────────────────────────────────────
  {
    id: 'sncb-m7',
    operator: 'SNCB',
    series: 'M7',
    uicClass: 'M7',
    manufacturer: 'Bombardier',
    introducedYear: 2019,
    maxSpeedKmh: 200,
    seats1st: 96,
    seats2nd: 480,
    hasBistro: false,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '3 kV DC, 25 kV AC',
    traction: 'Electric',
    description: 'SNCB M7 double-deck — new generation Belgian intercity coaches.',
    wikiUrl: 'https://en.wikipedia.org/wiki/SNCB/NMBS_M7',
    dataSource: 'seed',
  },
  {
    id: 'sncb-i11',
    operator: 'SNCB',
    series: 'I11',
    uicClass: 'I11',
    manufacturer: 'Bombardier',
    introducedYear: 2009,
    maxSpeedKmh: 200,
    seats1st: 60,
    seats2nd: 388,
    hasBistro: false,
    hasWifi: false,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '3 kV DC',
    traction: 'Electric',
    description: 'SNCB I11 single-deck intercity coaches, push-pull operation.',
    wikiUrl: 'https://en.wikipedia.org/wiki/SNCB/NMBS_I11',
    dataSource: 'seed',
  },

  // ── Czech Republic ────────────────────────────────────────────────────────
  {
    id: 'cd-railjet',
    operator: 'ČD',
    series: 'ČD Railjet',
    uicClass: 'RJ',
    manufacturer: 'Siemens Mobility',
    introducedYear: 2013,
    maxSpeedKmh: 230,
    seats1st: 76,
    seats2nd: 316,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC, 25 kV AC',
    traction: 'Electric',
    description: 'Czech Railways Railjet — same Viaggio Comfort stock as ÖBB.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Railjet',
    dataSource: 'seed',
  },
  {
    id: 'cd-viaggio',
    operator: 'ČD',
    series: 'Viaggio',
    uicClass: 'EC',
    manufacturer: 'Siemens Mobility',
    introducedYear: 2016,
    maxSpeedKmh: 200,
    seats1st: 60,
    seats2nd: 270,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '25 kV AC, 15 kV AC',
    traction: 'Electric',
    description: 'ČD Viaggio Comfort coaches for EC services Prague–Berlin.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Siemens_Viaggio',
    dataSource: 'seed',
  },

  // ── Poland ────────────────────────────────────────────────────────────────
  {
    id: 'pkp-pendolino',
    operator: 'PKP IC',
    series: 'PKP Pendolino',
    uicClass: '370',
    manufacturer: 'Alstom',
    introducedYear: 2014,
    maxSpeedKmh: 250,
    seats1st: 57,
    seats2nd: 348,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '3 kV DC, 25 kV AC',
    traction: 'Electric',
    description: 'ETR 610 Polish variant — PKP intercity flagship, Warsaw to Kraków/Gdańsk.',
    wikiUrl: 'https://en.wikipedia.org/wiki/PKP_Class_ED250',
    dataSource: 'seed',
  },
  {
    id: 'pkp-eip',
    operator: 'PKP IC',
    series: 'EIP',
    uicClass: 'EIP',
    manufacturer: 'Stadler Rail',
    introducedYear: 2022,
    maxSpeedKmh: 250,
    seats1st: 78,
    seats2nd: 328,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '3 kV DC, 25 kV AC',
    traction: 'Electric',
    description: 'PKP IC Express InterPendolino — Stadler FLIRT 200 for premium EIP routes.',
    wikiUrl: 'https://en.wikipedia.org/wiki/PKP_Intercity',
    dataSource: 'seed',
  },
  {
    id: 'pkp-dart',
    operator: 'PKP IC',
    series: 'Dart',
    uicClass: 'ED161',
    manufacturer: 'Pesa',
    introducedYear: 2014,
    maxSpeedKmh: 160,
    seats1st: 0,
    seats2nd: 232,
    hasBistro: false,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '3 kV DC',
    traction: 'Electric',
    description: 'Pesa Dart — Polish intercity EMU for IC and regional services.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Pesa_Dart',
    dataSource: 'seed',
  },

  // ── Sweden ────────────────────────────────────────────────────────────────
  {
    id: 'sj-x2000',
    operator: 'SJ',
    series: 'X 2000',
    uicClass: 'X2',
    manufacturer: 'ABB Asea Brown Boveri',
    introducedYear: 1990,
    maxSpeedKmh: 210,
    seats1st: 48,
    seats2nd: 245,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: '15 kV AC',
    traction: 'Electric Tilt',
    description: 'SJ X 2000 — Swedish tilting intercity, backbone of SJ long-distance.',
    wikiUrl: 'https://en.wikipedia.org/wiki/X_2000',
    dataSource: 'seed',
  },
  {
    id: 'sj-3000',
    operator: 'SJ',
    series: 'SJ 3000',
    uicClass: 'X62',
    manufacturer: 'Alstom',
    introducedYear: 2012,
    maxSpeedKmh: 250,
    seats1st: 60,
    seats2nd: 316,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC, 25 kV AC',
    traction: 'Electric',
    description: 'SJ 3000 — Swedish high-speed train for Stockholm–Gothenburg.',
    wikiUrl: 'https://en.wikipedia.org/wiki/SJ_3000',
    dataSource: 'seed',
  },

  // ── International / misc ──────────────────────────────────────────────────
  {
    id: 'en-generic',
    operator: 'Various',
    series: 'EuroNight',
    uicClass: 'EN',
    manufacturer: 'Various',
    introducedYear: 1993,
    maxSpeedKmh: 160,
    seats1st: 0,
    seats2nd: 0,
    hasBistro: false,
    hasWifi: false,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: 'Various',
    traction: 'Electric/Diesel',
    description: 'International overnight sleeper — seats, couchettes and sleeping cars.',
    wikiUrl: 'https://en.wikipedia.org/wiki/EuroNight',
    dataSource: 'seed',
  },
  {
    id: 'regiojet',
    operator: 'RegioJet',
    series: 'RegioJet',
    uicClass: 'RJ',
    manufacturer: 'Various',
    introducedYear: 2011,
    maxSpeedKmh: 160,
    seats1st: 60,
    seats2nd: 300,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: false,
    powerSystem: 'Electric/Diesel',
    traction: 'Locomotive-hauled',
    description: 'Czech private operator — refurbished coaches on Prague–Bratislava–Budapest.',
    wikiUrl: 'https://en.wikipedia.org/wiki/RegioJet',
    dataSource: 'seed',
  },
  {
    id: 'flixtrain',
    operator: 'Flixtrain',
    series: 'Flixtrain',
    uicClass: 'FLX',
    manufacturer: 'Various',
    introducedYear: 2018,
    maxSpeedKmh: 160,
    seats1st: 0,
    seats2nd: 450,
    hasBistro: false,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: 'Electric',
    traction: 'Locomotive-hauled',
    description: 'Budget intercity — classic coaches in Flixtrain livery, price-competitive.',
    wikiUrl: 'https://en.wikipedia.org/wiki/FlixTrain',
    dataSource: 'seed',
  },
  {
    id: 'westbahn',
    operator: 'Westbahn',
    series: 'Westbahn',
    uicClass: 'KISS',
    manufacturer: 'Stadler Rail',
    introducedYear: 2011,
    maxSpeedKmh: 230,
    seats1st: 60,
    seats2nd: 412,
    hasBistro: true,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: '15 kV AC',
    traction: 'Electric',
    description: 'Austrian private operator — Stadler KISS double-deck, Vienna–Salzburg.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Westbahn_(Austria)',
    dataSource: 'seed',
  },
  {
    id: 'flirt-generic',
    operator: 'Various',
    series: 'FLIRT',
    uicClass: 'FLIRT',
    manufacturer: 'Stadler Rail',
    introducedYear: 2004,
    maxSpeedKmh: 160,
    seats1st: 30,
    seats2nd: 120,
    hasBistro: false,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: 'Various',
    traction: 'Electric/Diesel',
    description: 'Swiss modular train family used across Europe.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Stadler_FLIRT',
    dataSource: 'seed',
  },
  {
    id: 'desiro-generic',
    operator: 'Various',
    series: 'Desiro',
    uicClass: 'Desiro',
    manufacturer: 'Siemens Mobility',
    introducedYear: 1998,
    maxSpeedKmh: 160,
    seats1st: 24,
    seats2nd: 144,
    hasBistro: false,
    hasWifi: true,
    hasWheelchair: true,
    hasBikeSpace: true,
    powerSystem: 'Various',
    traction: 'Electric/Diesel',
    description: 'German modular train family for regional services.',
    wikiUrl: 'https://en.wikipedia.org/wiki/Siemens_Desiro',
    dataSource: 'seed',
  },
]

async function main() {
  console.log('🚂 Seeding rolling stock data...')

  for (const stock of ROLLING_STOCK_DATA) {
    await prisma().rollingStock.upsert({
      where: { id: stock.id },
      update: stock,
      create: stock,
    })
    console.log(`✅ ${stock.series} (${stock.operator})`)
  }

  console.log(`\n✨ Rolling stock seeding complete! ${ROLLING_STOCK_DATA.length} entries upserted.`)
}

main()
  .catch((e) => {
    console.error('❌ Error seeding rolling stock:', e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma().$disconnect()
  })
